// Code generated by ent, DO NOT EDIT.

package crypto_prc_source

const (
	// Label holds the string label denoting the crypto_prc_source type in the database.
	Label = "crypto_prc_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeSourceOfCurrency holds the string denoting the source_of_currency edge name in mutations.
	EdgeSourceOfCurrency = "source_of_currency"
	// Table holds the table name of the crypto_prc_source in the database.
	Table = "crypto_prc_source"
	// SourceOfCurrencyTable is the table that holds the source_of_currency relation/edge.
	SourceOfCurrencyTable = "crypto_currency"
	// SourceOfCurrencyInverseTable is the table name for the CRYPTO_CURRENCY entity.
	// It exists in this package in order to avoid circular dependency with the "crypto_currency" package.
	SourceOfCurrencyInverseTable = "crypto_currency"
	// SourceOfCurrencyColumn is the table column denoting the source_of_currency relation/edge.
	SourceOfCurrencyColumn = "source_id"
)

// Columns holds all SQL columns for crypto_prc_source fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
