version: '3'
services:
  griffin_web2:
    build:
      dockerfile: ./Dockerfile
    network_mode: "host"
    ports:
      - "10433:10433"
    healthcheck:
      test: curl --fail http://0.0.0.0:10433/api/v0/ping || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5

