version: '3'
services:
  griffin_web2:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "10432:10432"
    healthcheck:
      test: curl --fail http://0.0.0.0:10432/ping || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5

