// Code generated by ent, DO NOT EDIT.

package crypto_currency

import (
	"griffin-dao/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Ticker applies equality check predicate on the "ticker" field. It's identical to TickerEQ.
func Ticker(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTicker), v))
	})
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSource), v))
	})
}

// TickerEQ applies the EQ predicate on the "ticker" field.
func TickerEQ(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTicker), v))
	})
}

// TickerNEQ applies the NEQ predicate on the "ticker" field.
func TickerNEQ(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTicker), v))
	})
}

// TickerIn applies the In predicate on the "ticker" field.
func TickerIn(vs ...string) predicate.CRYPTO_CURRENCY {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTicker), v...))
	})
}

// TickerNotIn applies the NotIn predicate on the "ticker" field.
func TickerNotIn(vs ...string) predicate.CRYPTO_CURRENCY {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTicker), v...))
	})
}

// TickerGT applies the GT predicate on the "ticker" field.
func TickerGT(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTicker), v))
	})
}

// TickerGTE applies the GTE predicate on the "ticker" field.
func TickerGTE(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTicker), v))
	})
}

// TickerLT applies the LT predicate on the "ticker" field.
func TickerLT(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTicker), v))
	})
}

// TickerLTE applies the LTE predicate on the "ticker" field.
func TickerLTE(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTicker), v))
	})
}

// TickerContains applies the Contains predicate on the "ticker" field.
func TickerContains(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTicker), v))
	})
}

// TickerHasPrefix applies the HasPrefix predicate on the "ticker" field.
func TickerHasPrefix(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTicker), v))
	})
}

// TickerHasSuffix applies the HasSuffix predicate on the "ticker" field.
func TickerHasSuffix(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTicker), v))
	})
}

// TickerEqualFold applies the EqualFold predicate on the "ticker" field.
func TickerEqualFold(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTicker), v))
	})
}

// TickerContainsFold applies the ContainsFold predicate on the "ticker" field.
func TickerContainsFold(v string) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTicker), v))
	})
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSource), v))
	})
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSource), v))
	})
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...int) predicate.CRYPTO_CURRENCY {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSource), v...))
	})
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...int) predicate.CRYPTO_CURRENCY {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSource), v...))
	})
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSource), v))
	})
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSource), v))
	})
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSource), v))
	})
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v int) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSource), v))
	})
}

// HasCryptoPrcSource applies the HasEdge predicate on the "crypto_prc_source" edge.
func HasCryptoPrcSource() predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CryptoPrcSourceTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CryptoPrcSourceTable, CryptoPrcSourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCryptoPrcSourceWith applies the HasEdge predicate on the "crypto_prc_source" edge with a given conditions (other predicates).
func HasCryptoPrcSourceWith(preds ...predicate.CRYPTO_PRC_SOURCE) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CryptoPrcSourceInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CryptoPrcSourceTable, CryptoPrcSourceColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CRYPTO_CURRENCY) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CRYPTO_CURRENCY) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CRYPTO_CURRENCY) predicate.CRYPTO_CURRENCY {
	return predicate.CRYPTO_CURRENCY(func(s *sql.Selector) {
		p(s.Not())
	})
}
