// Code generated by ent, DO NOT EDIT.

package payment_history

const (
	// Label holds the string label denoting the payment_history type in the database.
	Label = "payment_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmployeeID holds the string denoting the employee_id field in the database.
	FieldEmployeeID = "employee_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// EdgePaymentHistoryFromEmployee holds the string denoting the payment_history_from_employee edge name in mutations.
	EdgePaymentHistoryFromEmployee = "payment_history_from_employee"
	// Table holds the table name of the payment_history in the database.
	Table = "payment_history"
	// PaymentHistoryFromEmployeeTable is the table that holds the payment_history_from_employee relation/edge.
	PaymentHistoryFromEmployeeTable = "payment_history"
	// PaymentHistoryFromEmployeeInverseTable is the table name for the EMPLOYEE entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	PaymentHistoryFromEmployeeInverseTable = "employee"
	// PaymentHistoryFromEmployeeColumn is the table column denoting the payment_history_from_employee relation/edge.
	PaymentHistoryFromEmployeeColumn = "employee_id"
)

// Columns holds all SQL columns for payment_history fields.
var Columns = []string{
	FieldID,
	FieldEmployeeID,
	FieldCreatedAt,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
