// Code generated by ent, DO NOT EDIT.

package tr_log

import (
	"griffin-dao/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// TrType applies equality check predicate on the "tr_type" field. It's identical to TrTypeEQ.
func TrType(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTrType), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// TrTypeEQ applies the EQ predicate on the "tr_type" field.
func TrTypeEQ(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTrType), v))
	})
}

// TrTypeNEQ applies the NEQ predicate on the "tr_type" field.
func TrTypeNEQ(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTrType), v))
	})
}

// TrTypeIn applies the In predicate on the "tr_type" field.
func TrTypeIn(vs ...string) predicate.Tr_log {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTrType), v...))
	})
}

// TrTypeNotIn applies the NotIn predicate on the "tr_type" field.
func TrTypeNotIn(vs ...string) predicate.Tr_log {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTrType), v...))
	})
}

// TrTypeGT applies the GT predicate on the "tr_type" field.
func TrTypeGT(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTrType), v))
	})
}

// TrTypeGTE applies the GTE predicate on the "tr_type" field.
func TrTypeGTE(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTrType), v))
	})
}

// TrTypeLT applies the LT predicate on the "tr_type" field.
func TrTypeLT(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTrType), v))
	})
}

// TrTypeLTE applies the LTE predicate on the "tr_type" field.
func TrTypeLTE(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTrType), v))
	})
}

// TrTypeContains applies the Contains predicate on the "tr_type" field.
func TrTypeContains(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTrType), v))
	})
}

// TrTypeHasPrefix applies the HasPrefix predicate on the "tr_type" field.
func TrTypeHasPrefix(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTrType), v))
	})
}

// TrTypeHasSuffix applies the HasSuffix predicate on the "tr_type" field.
func TrTypeHasSuffix(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTrType), v))
	})
}

// TrTypeEqualFold applies the EqualFold predicate on the "tr_type" field.
func TrTypeEqualFold(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTrType), v))
	})
}

// TrTypeContainsFold applies the ContainsFold predicate on the "tr_type" field.
func TrTypeContainsFold(v string) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTrType), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tr_log {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tr_log {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tr_log) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tr_log) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tr_log) predicate.Tr_log {
	return predicate.Tr_log(func(s *sql.Selector) {
		p(s.Not())
	})
}
