// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"griffin-dao/ent/crypto_currency"
	"griffin-dao/ent/crypto_prc_source"
	"griffin-dao/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CRYPTOPRCSOURCEUpdate is the builder for updating CRYPTO_PRC_SOURCE entities.
type CRYPTOPRCSOURCEUpdate struct {
	config
	hooks    []Hook
	mutation *CRYPTOPRCSOURCEMutation
}

// Where appends a list predicates to the CRYPTOPRCSOURCEUpdate builder.
func (cu *CRYPTOPRCSOURCEUpdate) Where(ps ...predicate.CRYPTO_PRC_SOURCE) *CRYPTOPRCSOURCEUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetName sets the "name" field.
func (cu *CRYPTOPRCSOURCEUpdate) SetName(s string) *CRYPTOPRCSOURCEUpdate {
	cu.mutation.SetName(s)
	return cu
}

// AddSourceOfCurrencyIDs adds the "source_of_currency" edge to the CRYPTO_CURRENCY entity by IDs.
func (cu *CRYPTOPRCSOURCEUpdate) AddSourceOfCurrencyIDs(ids ...int) *CRYPTOPRCSOURCEUpdate {
	cu.mutation.AddSourceOfCurrencyIDs(ids...)
	return cu
}

// AddSourceOfCurrency adds the "source_of_currency" edges to the CRYPTO_CURRENCY entity.
func (cu *CRYPTOPRCSOURCEUpdate) AddSourceOfCurrency(c ...*CRYPTO_CURRENCY) *CRYPTOPRCSOURCEUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddSourceOfCurrencyIDs(ids...)
}

// Mutation returns the CRYPTOPRCSOURCEMutation object of the builder.
func (cu *CRYPTOPRCSOURCEUpdate) Mutation() *CRYPTOPRCSOURCEMutation {
	return cu.mutation
}

// ClearSourceOfCurrency clears all "source_of_currency" edges to the CRYPTO_CURRENCY entity.
func (cu *CRYPTOPRCSOURCEUpdate) ClearSourceOfCurrency() *CRYPTOPRCSOURCEUpdate {
	cu.mutation.ClearSourceOfCurrency()
	return cu
}

// RemoveSourceOfCurrencyIDs removes the "source_of_currency" edge to CRYPTO_CURRENCY entities by IDs.
func (cu *CRYPTOPRCSOURCEUpdate) RemoveSourceOfCurrencyIDs(ids ...int) *CRYPTOPRCSOURCEUpdate {
	cu.mutation.RemoveSourceOfCurrencyIDs(ids...)
	return cu
}

// RemoveSourceOfCurrency removes "source_of_currency" edges to CRYPTO_CURRENCY entities.
func (cu *CRYPTOPRCSOURCEUpdate) RemoveSourceOfCurrency(c ...*CRYPTO_CURRENCY) *CRYPTOPRCSOURCEUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveSourceOfCurrencyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CRYPTOPRCSOURCEUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CRYPTOPRCSOURCEMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CRYPTOPRCSOURCEUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CRYPTOPRCSOURCEUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CRYPTOPRCSOURCEUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CRYPTOPRCSOURCEUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   crypto_prc_source.Table,
			Columns: crypto_prc_source.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: crypto_prc_source.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: crypto_prc_source.FieldName,
		})
	}
	if cu.mutation.SourceOfCurrencyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_prc_source.SourceOfCurrencyTable,
			Columns: []string{crypto_prc_source.SourceOfCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_currency.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedSourceOfCurrencyIDs(); len(nodes) > 0 && !cu.mutation.SourceOfCurrencyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_prc_source.SourceOfCurrencyTable,
			Columns: []string{crypto_prc_source.SourceOfCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_currency.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.SourceOfCurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_prc_source.SourceOfCurrencyTable,
			Columns: []string{crypto_prc_source.SourceOfCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_currency.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{crypto_prc_source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// CRYPTOPRCSOURCEUpdateOne is the builder for updating a single CRYPTO_PRC_SOURCE entity.
type CRYPTOPRCSOURCEUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CRYPTOPRCSOURCEMutation
}

// SetName sets the "name" field.
func (cuo *CRYPTOPRCSOURCEUpdateOne) SetName(s string) *CRYPTOPRCSOURCEUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// AddSourceOfCurrencyIDs adds the "source_of_currency" edge to the CRYPTO_CURRENCY entity by IDs.
func (cuo *CRYPTOPRCSOURCEUpdateOne) AddSourceOfCurrencyIDs(ids ...int) *CRYPTOPRCSOURCEUpdateOne {
	cuo.mutation.AddSourceOfCurrencyIDs(ids...)
	return cuo
}

// AddSourceOfCurrency adds the "source_of_currency" edges to the CRYPTO_CURRENCY entity.
func (cuo *CRYPTOPRCSOURCEUpdateOne) AddSourceOfCurrency(c ...*CRYPTO_CURRENCY) *CRYPTOPRCSOURCEUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddSourceOfCurrencyIDs(ids...)
}

// Mutation returns the CRYPTOPRCSOURCEMutation object of the builder.
func (cuo *CRYPTOPRCSOURCEUpdateOne) Mutation() *CRYPTOPRCSOURCEMutation {
	return cuo.mutation
}

// ClearSourceOfCurrency clears all "source_of_currency" edges to the CRYPTO_CURRENCY entity.
func (cuo *CRYPTOPRCSOURCEUpdateOne) ClearSourceOfCurrency() *CRYPTOPRCSOURCEUpdateOne {
	cuo.mutation.ClearSourceOfCurrency()
	return cuo
}

// RemoveSourceOfCurrencyIDs removes the "source_of_currency" edge to CRYPTO_CURRENCY entities by IDs.
func (cuo *CRYPTOPRCSOURCEUpdateOne) RemoveSourceOfCurrencyIDs(ids ...int) *CRYPTOPRCSOURCEUpdateOne {
	cuo.mutation.RemoveSourceOfCurrencyIDs(ids...)
	return cuo
}

// RemoveSourceOfCurrency removes "source_of_currency" edges to CRYPTO_CURRENCY entities.
func (cuo *CRYPTOPRCSOURCEUpdateOne) RemoveSourceOfCurrency(c ...*CRYPTO_CURRENCY) *CRYPTOPRCSOURCEUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveSourceOfCurrencyIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CRYPTOPRCSOURCEUpdateOne) Select(field string, fields ...string) *CRYPTOPRCSOURCEUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated CRYPTO_PRC_SOURCE entity.
func (cuo *CRYPTOPRCSOURCEUpdateOne) Save(ctx context.Context) (*CRYPTO_PRC_SOURCE, error) {
	var (
		err  error
		node *CRYPTO_PRC_SOURCE
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CRYPTOPRCSOURCEMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CRYPTO_PRC_SOURCE)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CRYPTOPRCSOURCEMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CRYPTOPRCSOURCEUpdateOne) SaveX(ctx context.Context) *CRYPTO_PRC_SOURCE {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CRYPTOPRCSOURCEUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CRYPTOPRCSOURCEUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CRYPTOPRCSOURCEUpdateOne) sqlSave(ctx context.Context) (_node *CRYPTO_PRC_SOURCE, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   crypto_prc_source.Table,
			Columns: crypto_prc_source.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: crypto_prc_source.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CRYPTO_PRC_SOURCE.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, crypto_prc_source.FieldID)
		for _, f := range fields {
			if !crypto_prc_source.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != crypto_prc_source.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: crypto_prc_source.FieldName,
		})
	}
	if cuo.mutation.SourceOfCurrencyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_prc_source.SourceOfCurrencyTable,
			Columns: []string{crypto_prc_source.SourceOfCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_currency.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedSourceOfCurrencyIDs(); len(nodes) > 0 && !cuo.mutation.SourceOfCurrencyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_prc_source.SourceOfCurrencyTable,
			Columns: []string{crypto_prc_source.SourceOfCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_currency.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.SourceOfCurrencyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_prc_source.SourceOfCurrencyTable,
			Columns: []string{crypto_prc_source.SourceOfCurrencyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_currency.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CRYPTO_PRC_SOURCE{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{crypto_prc_source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
