// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"griffin-dao/ent/crypto_currency"
	"griffin-dao/ent/crypto_prc_source"
	"griffin-dao/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CRYPTOCURRENCYUpdate is the builder for updating CRYPTO_CURRENCY entities.
type CRYPTOCURRENCYUpdate struct {
	config
	hooks    []Hook
	mutation *CRYPTOCURRENCYMutation
}

// Where appends a list predicates to the CRYPTOCURRENCYUpdate builder.
func (cu *CRYPTOCURRENCYUpdate) Where(ps ...predicate.CRYPTO_CURRENCY) *CRYPTOCURRENCYUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetTicker sets the "ticker" field.
func (cu *CRYPTOCURRENCYUpdate) SetTicker(s string) *CRYPTOCURRENCYUpdate {
	cu.mutation.SetTicker(s)
	return cu
}

// SetSource sets the "source" field.
func (cu *CRYPTOCURRENCYUpdate) SetSource(i int) *CRYPTOCURRENCYUpdate {
	cu.mutation.ResetSource()
	cu.mutation.SetSource(i)
	return cu
}

// AddSource adds i to the "source" field.
func (cu *CRYPTOCURRENCYUpdate) AddSource(i int) *CRYPTOCURRENCYUpdate {
	cu.mutation.AddSource(i)
	return cu
}

// AddCryptoPrcSourceIDs adds the "crypto_prc_source" edge to the CRYPTO_PRC_SOURCE entity by IDs.
func (cu *CRYPTOCURRENCYUpdate) AddCryptoPrcSourceIDs(ids ...int) *CRYPTOCURRENCYUpdate {
	cu.mutation.AddCryptoPrcSourceIDs(ids...)
	return cu
}

// AddCryptoPrcSource adds the "crypto_prc_source" edges to the CRYPTO_PRC_SOURCE entity.
func (cu *CRYPTOCURRENCYUpdate) AddCryptoPrcSource(c ...*CRYPTO_PRC_SOURCE) *CRYPTOCURRENCYUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddCryptoPrcSourceIDs(ids...)
}

// Mutation returns the CRYPTOCURRENCYMutation object of the builder.
func (cu *CRYPTOCURRENCYUpdate) Mutation() *CRYPTOCURRENCYMutation {
	return cu.mutation
}

// ClearCryptoPrcSource clears all "crypto_prc_source" edges to the CRYPTO_PRC_SOURCE entity.
func (cu *CRYPTOCURRENCYUpdate) ClearCryptoPrcSource() *CRYPTOCURRENCYUpdate {
	cu.mutation.ClearCryptoPrcSource()
	return cu
}

// RemoveCryptoPrcSourceIDs removes the "crypto_prc_source" edge to CRYPTO_PRC_SOURCE entities by IDs.
func (cu *CRYPTOCURRENCYUpdate) RemoveCryptoPrcSourceIDs(ids ...int) *CRYPTOCURRENCYUpdate {
	cu.mutation.RemoveCryptoPrcSourceIDs(ids...)
	return cu
}

// RemoveCryptoPrcSource removes "crypto_prc_source" edges to CRYPTO_PRC_SOURCE entities.
func (cu *CRYPTOCURRENCYUpdate) RemoveCryptoPrcSource(c ...*CRYPTO_PRC_SOURCE) *CRYPTOCURRENCYUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveCryptoPrcSourceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CRYPTOCURRENCYUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CRYPTOCURRENCYMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CRYPTOCURRENCYUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CRYPTOCURRENCYUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CRYPTOCURRENCYUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CRYPTOCURRENCYUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   crypto_currency.Table,
			Columns: crypto_currency.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: crypto_currency.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Ticker(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: crypto_currency.FieldTicker,
		})
	}
	if value, ok := cu.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: crypto_currency.FieldSource,
		})
	}
	if value, ok := cu.mutation.AddedSource(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: crypto_currency.FieldSource,
		})
	}
	if cu.mutation.CryptoPrcSourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_currency.CryptoPrcSourceTable,
			Columns: []string{crypto_currency.CryptoPrcSourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_prc_source.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedCryptoPrcSourceIDs(); len(nodes) > 0 && !cu.mutation.CryptoPrcSourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_currency.CryptoPrcSourceTable,
			Columns: []string{crypto_currency.CryptoPrcSourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_prc_source.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CryptoPrcSourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_currency.CryptoPrcSourceTable,
			Columns: []string{crypto_currency.CryptoPrcSourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_prc_source.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{crypto_currency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// CRYPTOCURRENCYUpdateOne is the builder for updating a single CRYPTO_CURRENCY entity.
type CRYPTOCURRENCYUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CRYPTOCURRENCYMutation
}

// SetTicker sets the "ticker" field.
func (cuo *CRYPTOCURRENCYUpdateOne) SetTicker(s string) *CRYPTOCURRENCYUpdateOne {
	cuo.mutation.SetTicker(s)
	return cuo
}

// SetSource sets the "source" field.
func (cuo *CRYPTOCURRENCYUpdateOne) SetSource(i int) *CRYPTOCURRENCYUpdateOne {
	cuo.mutation.ResetSource()
	cuo.mutation.SetSource(i)
	return cuo
}

// AddSource adds i to the "source" field.
func (cuo *CRYPTOCURRENCYUpdateOne) AddSource(i int) *CRYPTOCURRENCYUpdateOne {
	cuo.mutation.AddSource(i)
	return cuo
}

// AddCryptoPrcSourceIDs adds the "crypto_prc_source" edge to the CRYPTO_PRC_SOURCE entity by IDs.
func (cuo *CRYPTOCURRENCYUpdateOne) AddCryptoPrcSourceIDs(ids ...int) *CRYPTOCURRENCYUpdateOne {
	cuo.mutation.AddCryptoPrcSourceIDs(ids...)
	return cuo
}

// AddCryptoPrcSource adds the "crypto_prc_source" edges to the CRYPTO_PRC_SOURCE entity.
func (cuo *CRYPTOCURRENCYUpdateOne) AddCryptoPrcSource(c ...*CRYPTO_PRC_SOURCE) *CRYPTOCURRENCYUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddCryptoPrcSourceIDs(ids...)
}

// Mutation returns the CRYPTOCURRENCYMutation object of the builder.
func (cuo *CRYPTOCURRENCYUpdateOne) Mutation() *CRYPTOCURRENCYMutation {
	return cuo.mutation
}

// ClearCryptoPrcSource clears all "crypto_prc_source" edges to the CRYPTO_PRC_SOURCE entity.
func (cuo *CRYPTOCURRENCYUpdateOne) ClearCryptoPrcSource() *CRYPTOCURRENCYUpdateOne {
	cuo.mutation.ClearCryptoPrcSource()
	return cuo
}

// RemoveCryptoPrcSourceIDs removes the "crypto_prc_source" edge to CRYPTO_PRC_SOURCE entities by IDs.
func (cuo *CRYPTOCURRENCYUpdateOne) RemoveCryptoPrcSourceIDs(ids ...int) *CRYPTOCURRENCYUpdateOne {
	cuo.mutation.RemoveCryptoPrcSourceIDs(ids...)
	return cuo
}

// RemoveCryptoPrcSource removes "crypto_prc_source" edges to CRYPTO_PRC_SOURCE entities.
func (cuo *CRYPTOCURRENCYUpdateOne) RemoveCryptoPrcSource(c ...*CRYPTO_PRC_SOURCE) *CRYPTOCURRENCYUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveCryptoPrcSourceIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CRYPTOCURRENCYUpdateOne) Select(field string, fields ...string) *CRYPTOCURRENCYUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated CRYPTO_CURRENCY entity.
func (cuo *CRYPTOCURRENCYUpdateOne) Save(ctx context.Context) (*CRYPTO_CURRENCY, error) {
	var (
		err  error
		node *CRYPTO_CURRENCY
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CRYPTOCURRENCYMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CRYPTO_CURRENCY)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CRYPTOCURRENCYMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CRYPTOCURRENCYUpdateOne) SaveX(ctx context.Context) *CRYPTO_CURRENCY {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CRYPTOCURRENCYUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CRYPTOCURRENCYUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CRYPTOCURRENCYUpdateOne) sqlSave(ctx context.Context) (_node *CRYPTO_CURRENCY, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   crypto_currency.Table,
			Columns: crypto_currency.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: crypto_currency.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CRYPTO_CURRENCY.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, crypto_currency.FieldID)
		for _, f := range fields {
			if !crypto_currency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != crypto_currency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Ticker(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: crypto_currency.FieldTicker,
		})
	}
	if value, ok := cuo.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: crypto_currency.FieldSource,
		})
	}
	if value, ok := cuo.mutation.AddedSource(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: crypto_currency.FieldSource,
		})
	}
	if cuo.mutation.CryptoPrcSourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_currency.CryptoPrcSourceTable,
			Columns: []string{crypto_currency.CryptoPrcSourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_prc_source.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedCryptoPrcSourceIDs(); len(nodes) > 0 && !cuo.mutation.CryptoPrcSourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_currency.CryptoPrcSourceTable,
			Columns: []string{crypto_currency.CryptoPrcSourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_prc_source.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CryptoPrcSourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   crypto_currency.CryptoPrcSourceTable,
			Columns: []string{crypto_currency.CryptoPrcSourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: crypto_prc_source.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CRYPTO_CURRENCY{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{crypto_currency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
