// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"griffin-dao/ent/crypto_currency"
	"griffin-dao/ent/crypto_prc_source"
	"griffin-dao/ent/employee"
	"griffin-dao/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CRYPTOCURRENCYQuery is the builder for querying CRYPTO_CURRENCY entities.
type CRYPTOCURRENCYQuery struct {
	config
	limit                *int
	offset               *int
	unique               *bool
	order                []OrderFunc
	fields               []string
	predicates           []predicate.CRYPTO_CURRENCY
	withSourceOf         *CRYPTOPRCSOURCEQuery
	withCurrencyEmployee *EMPLOYEEQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CRYPTOCURRENCYQuery builder.
func (cq *CRYPTOCURRENCYQuery) Where(ps ...predicate.CRYPTO_CURRENCY) *CRYPTOCURRENCYQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit adds a limit step to the query.
func (cq *CRYPTOCURRENCYQuery) Limit(limit int) *CRYPTOCURRENCYQuery {
	cq.limit = &limit
	return cq
}

// Offset adds an offset step to the query.
func (cq *CRYPTOCURRENCYQuery) Offset(offset int) *CRYPTOCURRENCYQuery {
	cq.offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CRYPTOCURRENCYQuery) Unique(unique bool) *CRYPTOCURRENCYQuery {
	cq.unique = &unique
	return cq
}

// Order adds an order step to the query.
func (cq *CRYPTOCURRENCYQuery) Order(o ...OrderFunc) *CRYPTOCURRENCYQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QuerySourceOf chains the current query on the "source_of" edge.
func (cq *CRYPTOCURRENCYQuery) QuerySourceOf() *CRYPTOPRCSOURCEQuery {
	query := &CRYPTOPRCSOURCEQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(crypto_currency.Table, crypto_currency.FieldID, selector),
			sqlgraph.To(crypto_prc_source.Table, crypto_prc_source.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, crypto_currency.SourceOfTable, crypto_currency.SourceOfColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCurrencyEmployee chains the current query on the "currency_employee" edge.
func (cq *CRYPTOCURRENCYQuery) QueryCurrencyEmployee() *EMPLOYEEQuery {
	query := &EMPLOYEEQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(crypto_currency.Table, crypto_currency.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, crypto_currency.CurrencyEmployeeTable, crypto_currency.CurrencyEmployeeColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CRYPTO_CURRENCY entity from the query.
// Returns a *NotFoundError when no CRYPTO_CURRENCY was found.
func (cq *CRYPTOCURRENCYQuery) First(ctx context.Context) (*CRYPTO_CURRENCY, error) {
	nodes, err := cq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{crypto_currency.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) FirstX(ctx context.Context) *CRYPTO_CURRENCY {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CRYPTO_CURRENCY ID from the query.
// Returns a *NotFoundError when no CRYPTO_CURRENCY ID was found.
func (cq *CRYPTOCURRENCYQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{crypto_currency.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CRYPTO_CURRENCY entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CRYPTO_CURRENCY entity is found.
// Returns a *NotFoundError when no CRYPTO_CURRENCY entities are found.
func (cq *CRYPTOCURRENCYQuery) Only(ctx context.Context) (*CRYPTO_CURRENCY, error) {
	nodes, err := cq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{crypto_currency.Label}
	default:
		return nil, &NotSingularError{crypto_currency.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) OnlyX(ctx context.Context) *CRYPTO_CURRENCY {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CRYPTO_CURRENCY ID in the query.
// Returns a *NotSingularError when more than one CRYPTO_CURRENCY ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CRYPTOCURRENCYQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{crypto_currency.Label}
	default:
		err = &NotSingularError{crypto_currency.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CRYPTO_CURRENCYs.
func (cq *CRYPTOCURRENCYQuery) All(ctx context.Context) ([]*CRYPTO_CURRENCY, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) AllX(ctx context.Context) []*CRYPTO_CURRENCY {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CRYPTO_CURRENCY IDs.
func (cq *CRYPTOCURRENCYQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := cq.Select(crypto_currency.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CRYPTOCURRENCYQuery) Count(ctx context.Context) (int, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CRYPTOCURRENCYQuery) Exist(ctx context.Context) (bool, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CRYPTOCURRENCYQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CRYPTOCURRENCYQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CRYPTOCURRENCYQuery) Clone() *CRYPTOCURRENCYQuery {
	if cq == nil {
		return nil
	}
	return &CRYPTOCURRENCYQuery{
		config:               cq.config,
		limit:                cq.limit,
		offset:               cq.offset,
		order:                append([]OrderFunc{}, cq.order...),
		predicates:           append([]predicate.CRYPTO_CURRENCY{}, cq.predicates...),
		withSourceOf:         cq.withSourceOf.Clone(),
		withCurrencyEmployee: cq.withCurrencyEmployee.Clone(),
		// clone intermediate query.
		sql:    cq.sql.Clone(),
		path:   cq.path,
		unique: cq.unique,
	}
}

// WithSourceOf tells the query-builder to eager-load the nodes that are connected to
// the "source_of" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CRYPTOCURRENCYQuery) WithSourceOf(opts ...func(*CRYPTOPRCSOURCEQuery)) *CRYPTOCURRENCYQuery {
	query := &CRYPTOPRCSOURCEQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withSourceOf = query
	return cq
}

// WithCurrencyEmployee tells the query-builder to eager-load the nodes that are connected to
// the "currency_employee" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CRYPTOCURRENCYQuery) WithCurrencyEmployee(opts ...func(*EMPLOYEEQuery)) *CRYPTOCURRENCYQuery {
	query := &EMPLOYEEQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withCurrencyEmployee = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Ticker string `json:"ticker,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CRYPTOCURRENCY.Query().
//		GroupBy(crypto_currency.FieldTicker).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CRYPTOCURRENCYQuery) GroupBy(field string, fields ...string) *CRYPTOCURRENCYGroupBy {
	grbuild := &CRYPTOCURRENCYGroupBy{config: cq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cq.sqlQuery(ctx), nil
	}
	grbuild.label = crypto_currency.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Ticker string `json:"ticker,omitempty"`
//	}
//
//	client.CRYPTOCURRENCY.Query().
//		Select(crypto_currency.FieldTicker).
//		Scan(ctx, &v)
func (cq *CRYPTOCURRENCYQuery) Select(fields ...string) *CRYPTOCURRENCYSelect {
	cq.fields = append(cq.fields, fields...)
	selbuild := &CRYPTOCURRENCYSelect{CRYPTOCURRENCYQuery: cq}
	selbuild.label = crypto_currency.Label
	selbuild.flds, selbuild.scan = &cq.fields, selbuild.Scan
	return selbuild
}

func (cq *CRYPTOCURRENCYQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cq.fields {
		if !crypto_currency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CRYPTOCURRENCYQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CRYPTO_CURRENCY, error) {
	var (
		nodes       = []*CRYPTO_CURRENCY{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [2]bool{
			cq.withSourceOf != nil,
			cq.withCurrencyEmployee != nil,
		}
	)
	if cq.withSourceOf != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, crypto_currency.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*CRYPTO_CURRENCY).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &CRYPTO_CURRENCY{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withSourceOf; query != nil {
		if err := cq.loadSourceOf(ctx, query, nodes, nil,
			func(n *CRYPTO_CURRENCY, e *CRYPTO_PRC_SOURCE) { n.Edges.SourceOf = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withCurrencyEmployee; query != nil {
		if err := cq.loadCurrencyEmployee(ctx, query, nodes,
			func(n *CRYPTO_CURRENCY) { n.Edges.CurrencyEmployee = []*EMPLOYEE{} },
			func(n *CRYPTO_CURRENCY, e *EMPLOYEE) { n.Edges.CurrencyEmployee = append(n.Edges.CurrencyEmployee, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CRYPTOCURRENCYQuery) loadSourceOf(ctx context.Context, query *CRYPTOPRCSOURCEQuery, nodes []*CRYPTO_CURRENCY, init func(*CRYPTO_CURRENCY), assign func(*CRYPTO_CURRENCY, *CRYPTO_PRC_SOURCE)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CRYPTO_CURRENCY)
	for i := range nodes {
		if nodes[i].crypto_prc_source_price_of == nil {
			continue
		}
		fk := *nodes[i].crypto_prc_source_price_of
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(crypto_prc_source.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "crypto_prc_source_price_of" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CRYPTOCURRENCYQuery) loadCurrencyEmployee(ctx context.Context, query *EMPLOYEEQuery, nodes []*CRYPTO_CURRENCY, init func(*CRYPTO_CURRENCY), assign func(*CRYPTO_CURRENCY, *EMPLOYEE)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CRYPTO_CURRENCY)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.EMPLOYEE(func(s *sql.Selector) {
		s.Where(sql.InValues(crypto_currency.CurrencyEmployeeColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.Currency
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "currency" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *CRYPTOCURRENCYQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.fields
	if len(cq.fields) > 0 {
		_spec.Unique = cq.unique != nil && *cq.unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CRYPTOCURRENCYQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cq *CRYPTOCURRENCYQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   crypto_currency.Table,
			Columns: crypto_currency.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: crypto_currency.FieldID,
			},
		},
		From:   cq.sql,
		Unique: true,
	}
	if unique := cq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, crypto_currency.FieldID)
		for i := range fields {
			if fields[i] != crypto_currency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CRYPTOCURRENCYQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(crypto_currency.Table)
	columns := cq.fields
	if len(columns) == 0 {
		columns = crypto_currency.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.unique != nil && *cq.unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CRYPTOCURRENCYGroupBy is the group-by builder for CRYPTO_CURRENCY entities.
type CRYPTOCURRENCYGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CRYPTOCURRENCYGroupBy) Aggregate(fns ...AggregateFunc) *CRYPTOCURRENCYGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the group-by query and scans the result into the given value.
func (cgb *CRYPTOCURRENCYGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cgb.path(ctx)
	if err != nil {
		return err
	}
	cgb.sql = query
	return cgb.sqlScan(ctx, v)
}

func (cgb *CRYPTOCURRENCYGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cgb.fields {
		if !crypto_currency.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cgb *CRYPTOCURRENCYGroupBy) sqlQuery() *sql.Selector {
	selector := cgb.sql.Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cgb.fields)+len(cgb.fns))
		for _, f := range cgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cgb.fields...)...)
}

// CRYPTOCURRENCYSelect is the builder for selecting fields of CRYPTOCURRENCY entities.
type CRYPTOCURRENCYSelect struct {
	*CRYPTOCURRENCYQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CRYPTOCURRENCYSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	cs.sql = cs.CRYPTOCURRENCYQuery.sqlQuery(ctx)
	return cs.sqlScan(ctx, v)
}

func (cs *CRYPTOCURRENCYSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cs.sql.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
