// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"griffin-dao/ent/employee"
	"griffin-dao/ent/employer_user_info"
	"griffin-dao/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EMPLOYERUSERINFOUpdate is the builder for updating EMPLOYER_USER_INFO entities.
type EMPLOYERUSERINFOUpdate struct {
	config
	hooks    []Hook
	mutation *EMPLOYERUSERINFOMutation
}

// Where appends a list predicates to the EMPLOYERUSERINFOUpdate builder.
func (eu *EMPLOYERUSERINFOUpdate) Where(ps ...predicate.EMPLOYER_USER_INFO) *EMPLOYERUSERINFOUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUsername sets the "username" field.
func (eu *EMPLOYERUSERINFOUpdate) SetUsername(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetUsername(s)
	return eu
}

// SetPassword sets the "password" field.
func (eu *EMPLOYERUSERINFOUpdate) SetPassword(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetPassword(s)
	return eu
}

// SetGid sets the "gid" field.
func (eu *EMPLOYERUSERINFOUpdate) SetGid(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetGid(s)
	return eu
}

// SetCorpName sets the "corp_name" field.
func (eu *EMPLOYERUSERINFOUpdate) SetCorpName(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetCorpName(s)
	return eu
}

// SetCorpEmail sets the "corp_email" field.
func (eu *EMPLOYERUSERINFOUpdate) SetCorpEmail(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetCorpEmail(s)
	return eu
}

// SetWallet sets the "wallet" field.
func (eu *EMPLOYERUSERINFOUpdate) SetWallet(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetWallet(s)
	return eu
}

// SetCreatedAt sets the "created_at" field.
func (eu *EMPLOYERUSERINFOUpdate) SetCreatedAt(t time.Time) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetCreatedAt(t)
	return eu
}

// SetCreatedBy sets the "created_by" field.
func (eu *EMPLOYERUSERINFOUpdate) SetCreatedBy(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetCreatedBy(s)
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *EMPLOYERUSERINFOUpdate) SetUpdatedAt(t time.Time) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// SetUpdatedBy sets the "updated_by" field.
func (eu *EMPLOYERUSERINFOUpdate) SetUpdatedBy(s string) *EMPLOYERUSERINFOUpdate {
	eu.mutation.SetUpdatedBy(s)
	return eu
}

// AddWorkUnderIDs adds the "work_under" edge to the EMPLOYEE entity by IDs.
func (eu *EMPLOYERUSERINFOUpdate) AddWorkUnderIDs(ids ...int) *EMPLOYERUSERINFOUpdate {
	eu.mutation.AddWorkUnderIDs(ids...)
	return eu
}

// AddWorkUnder adds the "work_under" edges to the EMPLOYEE entity.
func (eu *EMPLOYERUSERINFOUpdate) AddWorkUnder(e ...*EMPLOYEE) *EMPLOYERUSERINFOUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.AddWorkUnderIDs(ids...)
}

// Mutation returns the EMPLOYERUSERINFOMutation object of the builder.
func (eu *EMPLOYERUSERINFOUpdate) Mutation() *EMPLOYERUSERINFOMutation {
	return eu.mutation
}

// ClearWorkUnder clears all "work_under" edges to the EMPLOYEE entity.
func (eu *EMPLOYERUSERINFOUpdate) ClearWorkUnder() *EMPLOYERUSERINFOUpdate {
	eu.mutation.ClearWorkUnder()
	return eu
}

// RemoveWorkUnderIDs removes the "work_under" edge to EMPLOYEE entities by IDs.
func (eu *EMPLOYERUSERINFOUpdate) RemoveWorkUnderIDs(ids ...int) *EMPLOYERUSERINFOUpdate {
	eu.mutation.RemoveWorkUnderIDs(ids...)
	return eu
}

// RemoveWorkUnder removes "work_under" edges to EMPLOYEE entities.
func (eu *EMPLOYERUSERINFOUpdate) RemoveWorkUnder(e ...*EMPLOYEE) *EMPLOYERUSERINFOUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.RemoveWorkUnderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EMPLOYERUSERINFOUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EMPLOYERUSERINFOMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			if eu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EMPLOYERUSERINFOUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EMPLOYERUSERINFOUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EMPLOYERUSERINFOUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *EMPLOYERUSERINFOUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   employer_user_info.Table,
			Columns: employer_user_info.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employer_user_info.FieldID,
			},
		},
	}
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldUsername,
		})
	}
	if value, ok := eu.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldPassword,
		})
	}
	if value, ok := eu.mutation.Gid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldGid,
		})
	}
	if value, ok := eu.mutation.CorpName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldCorpName,
		})
	}
	if value, ok := eu.mutation.CorpEmail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldCorpEmail,
		})
	}
	if value, ok := eu.mutation.Wallet(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldWallet,
		})
	}
	if value, ok := eu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employer_user_info.FieldCreatedAt,
		})
	}
	if value, ok := eu.mutation.CreatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldCreatedBy,
		})
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employer_user_info.FieldUpdatedAt,
		})
	}
	if value, ok := eu.mutation.UpdatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldUpdatedBy,
		})
	}
	if eu.mutation.WorkUnderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employer_user_info.WorkUnderTable,
			Columns: []string{employer_user_info.WorkUnderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedWorkUnderIDs(); len(nodes) > 0 && !eu.mutation.WorkUnderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employer_user_info.WorkUnderTable,
			Columns: []string{employer_user_info.WorkUnderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.WorkUnderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employer_user_info.WorkUnderTable,
			Columns: []string{employer_user_info.WorkUnderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employer_user_info.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// EMPLOYERUSERINFOUpdateOne is the builder for updating a single EMPLOYER_USER_INFO entity.
type EMPLOYERUSERINFOUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EMPLOYERUSERINFOMutation
}

// SetUsername sets the "username" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetUsername(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetUsername(s)
	return euo
}

// SetPassword sets the "password" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetPassword(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetPassword(s)
	return euo
}

// SetGid sets the "gid" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetGid(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetGid(s)
	return euo
}

// SetCorpName sets the "corp_name" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetCorpName(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetCorpName(s)
	return euo
}

// SetCorpEmail sets the "corp_email" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetCorpEmail(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetCorpEmail(s)
	return euo
}

// SetWallet sets the "wallet" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetWallet(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetWallet(s)
	return euo
}

// SetCreatedAt sets the "created_at" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetCreatedAt(t time.Time) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetCreatedAt(t)
	return euo
}

// SetCreatedBy sets the "created_by" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetCreatedBy(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetCreatedBy(s)
	return euo
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetUpdatedAt(t time.Time) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// SetUpdatedBy sets the "updated_by" field.
func (euo *EMPLOYERUSERINFOUpdateOne) SetUpdatedBy(s string) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.SetUpdatedBy(s)
	return euo
}

// AddWorkUnderIDs adds the "work_under" edge to the EMPLOYEE entity by IDs.
func (euo *EMPLOYERUSERINFOUpdateOne) AddWorkUnderIDs(ids ...int) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.AddWorkUnderIDs(ids...)
	return euo
}

// AddWorkUnder adds the "work_under" edges to the EMPLOYEE entity.
func (euo *EMPLOYERUSERINFOUpdateOne) AddWorkUnder(e ...*EMPLOYEE) *EMPLOYERUSERINFOUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.AddWorkUnderIDs(ids...)
}

// Mutation returns the EMPLOYERUSERINFOMutation object of the builder.
func (euo *EMPLOYERUSERINFOUpdateOne) Mutation() *EMPLOYERUSERINFOMutation {
	return euo.mutation
}

// ClearWorkUnder clears all "work_under" edges to the EMPLOYEE entity.
func (euo *EMPLOYERUSERINFOUpdateOne) ClearWorkUnder() *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.ClearWorkUnder()
	return euo
}

// RemoveWorkUnderIDs removes the "work_under" edge to EMPLOYEE entities by IDs.
func (euo *EMPLOYERUSERINFOUpdateOne) RemoveWorkUnderIDs(ids ...int) *EMPLOYERUSERINFOUpdateOne {
	euo.mutation.RemoveWorkUnderIDs(ids...)
	return euo
}

// RemoveWorkUnder removes "work_under" edges to EMPLOYEE entities.
func (euo *EMPLOYERUSERINFOUpdateOne) RemoveWorkUnder(e ...*EMPLOYEE) *EMPLOYERUSERINFOUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.RemoveWorkUnderIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EMPLOYERUSERINFOUpdateOne) Select(field string, fields ...string) *EMPLOYERUSERINFOUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated EMPLOYER_USER_INFO entity.
func (euo *EMPLOYERUSERINFOUpdateOne) Save(ctx context.Context) (*EMPLOYER_USER_INFO, error) {
	var (
		err  error
		node *EMPLOYER_USER_INFO
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EMPLOYERUSERINFOMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			if euo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = euo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, euo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*EMPLOYER_USER_INFO)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EMPLOYERUSERINFOMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EMPLOYERUSERINFOUpdateOne) SaveX(ctx context.Context) *EMPLOYER_USER_INFO {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EMPLOYERUSERINFOUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EMPLOYERUSERINFOUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *EMPLOYERUSERINFOUpdateOne) sqlSave(ctx context.Context) (_node *EMPLOYER_USER_INFO, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   employer_user_info.Table,
			Columns: employer_user_info.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employer_user_info.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EMPLOYER_USER_INFO.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employer_user_info.FieldID)
		for _, f := range fields {
			if !employer_user_info.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != employer_user_info.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Username(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldUsername,
		})
	}
	if value, ok := euo.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldPassword,
		})
	}
	if value, ok := euo.mutation.Gid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldGid,
		})
	}
	if value, ok := euo.mutation.CorpName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldCorpName,
		})
	}
	if value, ok := euo.mutation.CorpEmail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldCorpEmail,
		})
	}
	if value, ok := euo.mutation.Wallet(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldWallet,
		})
	}
	if value, ok := euo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employer_user_info.FieldCreatedAt,
		})
	}
	if value, ok := euo.mutation.CreatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldCreatedBy,
		})
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: employer_user_info.FieldUpdatedAt,
		})
	}
	if value, ok := euo.mutation.UpdatedBy(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employer_user_info.FieldUpdatedBy,
		})
	}
	if euo.mutation.WorkUnderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employer_user_info.WorkUnderTable,
			Columns: []string{employer_user_info.WorkUnderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedWorkUnderIDs(); len(nodes) > 0 && !euo.mutation.WorkUnderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employer_user_info.WorkUnderTable,
			Columns: []string{employer_user_info.WorkUnderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.WorkUnderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employer_user_info.WorkUnderTable,
			Columns: []string{employer_user_info.WorkUnderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EMPLOYER_USER_INFO{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employer_user_info.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
