// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"griffin-dao/ent/employ_type"
	"griffin-dao/ent/employee"
	"griffin-dao/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EMPLOYTYPEQuery is the builder for querying EMPLOY_TYPE entities.
type EMPLOYTYPEQuery struct {
	config
	limit              *int
	offset             *int
	unique             *bool
	order              []OrderFunc
	fields             []string
	predicates         []predicate.EMPLOY_TYPE
	withEmployeeTypeTo *EMPLOYEEQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EMPLOYTYPEQuery builder.
func (eq *EMPLOYTYPEQuery) Where(ps ...predicate.EMPLOY_TYPE) *EMPLOYTYPEQuery {
	eq.predicates = append(eq.predicates, ps...)
	return eq
}

// Limit adds a limit step to the query.
func (eq *EMPLOYTYPEQuery) Limit(limit int) *EMPLOYTYPEQuery {
	eq.limit = &limit
	return eq
}

// Offset adds an offset step to the query.
func (eq *EMPLOYTYPEQuery) Offset(offset int) *EMPLOYTYPEQuery {
	eq.offset = &offset
	return eq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eq *EMPLOYTYPEQuery) Unique(unique bool) *EMPLOYTYPEQuery {
	eq.unique = &unique
	return eq
}

// Order adds an order step to the query.
func (eq *EMPLOYTYPEQuery) Order(o ...OrderFunc) *EMPLOYTYPEQuery {
	eq.order = append(eq.order, o...)
	return eq
}

// QueryEmployeeTypeTo chains the current query on the "employee_type_to" edge.
func (eq *EMPLOYTYPEQuery) QueryEmployeeTypeTo() *EMPLOYEEQuery {
	query := &EMPLOYEEQuery{config: eq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(employ_type.Table, employ_type.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, employ_type.EmployeeTypeToTable, employ_type.EmployeeTypeToColumn),
		)
		fromU = sqlgraph.SetNeighbors(eq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EMPLOY_TYPE entity from the query.
// Returns a *NotFoundError when no EMPLOY_TYPE was found.
func (eq *EMPLOYTYPEQuery) First(ctx context.Context) (*EMPLOY_TYPE, error) {
	nodes, err := eq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{employ_type.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) FirstX(ctx context.Context) *EMPLOY_TYPE {
	node, err := eq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EMPLOY_TYPE ID from the query.
// Returns a *NotFoundError when no EMPLOY_TYPE ID was found.
func (eq *EMPLOYTYPEQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{employ_type.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) FirstIDX(ctx context.Context) int {
	id, err := eq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EMPLOY_TYPE entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EMPLOY_TYPE entity is found.
// Returns a *NotFoundError when no EMPLOY_TYPE entities are found.
func (eq *EMPLOYTYPEQuery) Only(ctx context.Context) (*EMPLOY_TYPE, error) {
	nodes, err := eq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{employ_type.Label}
	default:
		return nil, &NotSingularError{employ_type.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) OnlyX(ctx context.Context) *EMPLOY_TYPE {
	node, err := eq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EMPLOY_TYPE ID in the query.
// Returns a *NotSingularError when more than one EMPLOY_TYPE ID is found.
// Returns a *NotFoundError when no entities are found.
func (eq *EMPLOYTYPEQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{employ_type.Label}
	default:
		err = &NotSingularError{employ_type.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) OnlyIDX(ctx context.Context) int {
	id, err := eq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EMPLOY_TYPEs.
func (eq *EMPLOYTYPEQuery) All(ctx context.Context) ([]*EMPLOY_TYPE, error) {
	if err := eq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return eq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) AllX(ctx context.Context) []*EMPLOY_TYPE {
	nodes, err := eq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EMPLOY_TYPE IDs.
func (eq *EMPLOYTYPEQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := eq.Select(employ_type.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) IDsX(ctx context.Context) []int {
	ids, err := eq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eq *EMPLOYTYPEQuery) Count(ctx context.Context) (int, error) {
	if err := eq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return eq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) CountX(ctx context.Context) int {
	count, err := eq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eq *EMPLOYTYPEQuery) Exist(ctx context.Context) (bool, error) {
	if err := eq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return eq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (eq *EMPLOYTYPEQuery) ExistX(ctx context.Context) bool {
	exist, err := eq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EMPLOYTYPEQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eq *EMPLOYTYPEQuery) Clone() *EMPLOYTYPEQuery {
	if eq == nil {
		return nil
	}
	return &EMPLOYTYPEQuery{
		config:             eq.config,
		limit:              eq.limit,
		offset:             eq.offset,
		order:              append([]OrderFunc{}, eq.order...),
		predicates:         append([]predicate.EMPLOY_TYPE{}, eq.predicates...),
		withEmployeeTypeTo: eq.withEmployeeTypeTo.Clone(),
		// clone intermediate query.
		sql:    eq.sql.Clone(),
		path:   eq.path,
		unique: eq.unique,
	}
}

// WithEmployeeTypeTo tells the query-builder to eager-load the nodes that are connected to
// the "employee_type_to" edge. The optional arguments are used to configure the query builder of the edge.
func (eq *EMPLOYTYPEQuery) WithEmployeeTypeTo(opts ...func(*EMPLOYEEQuery)) *EMPLOYTYPEQuery {
	query := &EMPLOYEEQuery{config: eq.config}
	for _, opt := range opts {
		opt(query)
	}
	eq.withEmployeeTypeTo = query
	return eq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IsPermanent string `json:"is_permanent,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EMPLOYTYPE.Query().
//		GroupBy(employ_type.FieldIsPermanent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eq *EMPLOYTYPEQuery) GroupBy(field string, fields ...string) *EMPLOYTYPEGroupBy {
	grbuild := &EMPLOYTYPEGroupBy{config: eq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := eq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return eq.sqlQuery(ctx), nil
	}
	grbuild.label = employ_type.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IsPermanent string `json:"is_permanent,omitempty"`
//	}
//
//	client.EMPLOYTYPE.Query().
//		Select(employ_type.FieldIsPermanent).
//		Scan(ctx, &v)
func (eq *EMPLOYTYPEQuery) Select(fields ...string) *EMPLOYTYPESelect {
	eq.fields = append(eq.fields, fields...)
	selbuild := &EMPLOYTYPESelect{EMPLOYTYPEQuery: eq}
	selbuild.label = employ_type.Label
	selbuild.flds, selbuild.scan = &eq.fields, selbuild.Scan
	return selbuild
}

func (eq *EMPLOYTYPEQuery) prepareQuery(ctx context.Context) error {
	for _, f := range eq.fields {
		if !employ_type.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eq.path != nil {
		prev, err := eq.path(ctx)
		if err != nil {
			return err
		}
		eq.sql = prev
	}
	return nil
}

func (eq *EMPLOYTYPEQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EMPLOY_TYPE, error) {
	var (
		nodes       = []*EMPLOY_TYPE{}
		_spec       = eq.querySpec()
		loadedTypes = [1]bool{
			eq.withEmployeeTypeTo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*EMPLOY_TYPE).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &EMPLOY_TYPE{config: eq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eq.withEmployeeTypeTo; query != nil {
		if err := eq.loadEmployeeTypeTo(ctx, query, nodes,
			func(n *EMPLOY_TYPE) { n.Edges.EmployeeTypeTo = []*EMPLOYEE{} },
			func(n *EMPLOY_TYPE, e *EMPLOYEE) { n.Edges.EmployeeTypeTo = append(n.Edges.EmployeeTypeTo, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eq *EMPLOYTYPEQuery) loadEmployeeTypeTo(ctx context.Context, query *EMPLOYEEQuery, nodes []*EMPLOY_TYPE, init func(*EMPLOY_TYPE), assign func(*EMPLOY_TYPE, *EMPLOYEE)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*EMPLOY_TYPE)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.EMPLOYEE(func(s *sql.Selector) {
		s.Where(sql.InValues(employ_type.EmployeeTypeToColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.employ_type_employee_type_to
		if fk == nil {
			return fmt.Errorf(`foreign-key "employ_type_employee_type_to" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "employ_type_employee_type_to" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (eq *EMPLOYTYPEQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eq.querySpec()
	_spec.Node.Columns = eq.fields
	if len(eq.fields) > 0 {
		_spec.Unique = eq.unique != nil && *eq.unique
	}
	return sqlgraph.CountNodes(ctx, eq.driver, _spec)
}

func (eq *EMPLOYTYPEQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := eq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (eq *EMPLOYTYPEQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   employ_type.Table,
			Columns: employ_type.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employ_type.FieldID,
			},
		},
		From:   eq.sql,
		Unique: true,
	}
	if unique := eq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := eq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employ_type.FieldID)
		for i := range fields {
			if fields[i] != employ_type.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eq *EMPLOYTYPEQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eq.driver.Dialect())
	t1 := builder.Table(employ_type.Table)
	columns := eq.fields
	if len(columns) == 0 {
		columns = employ_type.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eq.sql != nil {
		selector = eq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eq.unique != nil && *eq.unique {
		selector.Distinct()
	}
	for _, p := range eq.predicates {
		p(selector)
	}
	for _, p := range eq.order {
		p(selector)
	}
	if offset := eq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EMPLOYTYPEGroupBy is the group-by builder for EMPLOY_TYPE entities.
type EMPLOYTYPEGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (egb *EMPLOYTYPEGroupBy) Aggregate(fns ...AggregateFunc) *EMPLOYTYPEGroupBy {
	egb.fns = append(egb.fns, fns...)
	return egb
}

// Scan applies the group-by query and scans the result into the given value.
func (egb *EMPLOYTYPEGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := egb.path(ctx)
	if err != nil {
		return err
	}
	egb.sql = query
	return egb.sqlScan(ctx, v)
}

func (egb *EMPLOYTYPEGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range egb.fields {
		if !employ_type.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := egb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := egb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (egb *EMPLOYTYPEGroupBy) sqlQuery() *sql.Selector {
	selector := egb.sql.Select()
	aggregation := make([]string, 0, len(egb.fns))
	for _, fn := range egb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(egb.fields)+len(egb.fns))
		for _, f := range egb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(egb.fields...)...)
}

// EMPLOYTYPESelect is the builder for selecting fields of EMPLOYTYPE entities.
type EMPLOYTYPESelect struct {
	*EMPLOYTYPEQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (es *EMPLOYTYPESelect) Scan(ctx context.Context, v interface{}) error {
	if err := es.prepareQuery(ctx); err != nil {
		return err
	}
	es.sql = es.EMPLOYTYPEQuery.sqlQuery(ctx)
	return es.sqlScan(ctx, v)
}

func (es *EMPLOYTYPESelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := es.sql.Query()
	if err := es.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
