// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"griffin-dao/ent/employer_user_info"
	"griffin-dao/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EMPLOYERUSERINFODelete is the builder for deleting a EMPLOYER_USER_INFO entity.
type EMPLOYERUSERINFODelete struct {
	config
	hooks    []Hook
	mutation *EMPLOYERUSERINFOMutation
}

// Where appends a list predicates to the EMPLOYERUSERINFODelete builder.
func (ed *EMPLOYERUSERINFODelete) Where(ps ...predicate.EMPLOYER_USER_INFO) *EMPLOYERUSERINFODelete {
	ed.mutation.Where(ps...)
	return ed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ed *EMPLOYERUSERINFODelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ed.hooks) == 0 {
		affected, err = ed.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EMPLOYERUSERINFOMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ed.mutation = mutation
			affected, err = ed.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ed.hooks) - 1; i >= 0; i-- {
			if ed.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ed.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ed.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ed *EMPLOYERUSERINFODelete) ExecX(ctx context.Context) int {
	n, err := ed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ed *EMPLOYERUSERINFODelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: employer_user_info.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employer_user_info.FieldID,
			},
		},
	}
	if ps := ed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// EMPLOYERUSERINFODeleteOne is the builder for deleting a single EMPLOYER_USER_INFO entity.
type EMPLOYERUSERINFODeleteOne struct {
	ed *EMPLOYERUSERINFODelete
}

// Exec executes the deletion query.
func (edo *EMPLOYERUSERINFODeleteOne) Exec(ctx context.Context) error {
	n, err := edo.ed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{employer_user_info.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (edo *EMPLOYERUSERINFODeleteOne) ExecX(ctx context.Context) {
	edo.ed.ExecX(ctx)
}
