// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"griffin-dao/ent/employ_type"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// EMPLOY_TYPE is the model entity for the EMPLOY_TYPE schema.
type EMPLOY_TYPE struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EMPLOY_TYPE) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case employ_type.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EMPLOY_TYPE", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EMPLOY_TYPE fields.
func (et *EMPLOY_TYPE) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case employ_type.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			et.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this EMPLOY_TYPE.
// Note that you need to call EMPLOY_TYPE.Unwrap() before calling this method if this EMPLOY_TYPE
// was returned from a transaction, and the transaction was committed or rolled back.
func (et *EMPLOY_TYPE) Update() *EMPLOYTYPEUpdateOne {
	return (&EMPLOY_TYPEClient{config: et.config}).UpdateOne(et)
}

// Unwrap unwraps the EMPLOY_TYPE entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (et *EMPLOY_TYPE) Unwrap() *EMPLOY_TYPE {
	_tx, ok := et.config.driver.(*txDriver)
	if !ok {
		panic("ent: EMPLOY_TYPE is not a transactional entity")
	}
	et.config.driver = _tx.drv
	return et
}

// String implements the fmt.Stringer.
func (et *EMPLOY_TYPE) String() string {
	var builder strings.Builder
	builder.WriteString("EMPLOY_TYPE(")
	builder.WriteString(fmt.Sprintf("id=%v", et.ID))
	builder.WriteByte(')')
	return builder.String()
}

// EMPLOY_TYPEs is a parsable slice of EMPLOY_TYPE.
type EMPLOY_TYPEs []*EMPLOY_TYPE

func (et EMPLOY_TYPEs) config(cfg config) {
	for _i := range et {
		et[_i].config = cfg
	}
}
