// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"griffin-dao/ent/employer_user_info"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EMPLOYERUSERINFOCreate is the builder for creating a EMPLOYER_USER_INFO entity.
type EMPLOYERUSERINFOCreate struct {
	config
	mutation *EMPLOYERUSERINFOMutation
	hooks    []Hook
}

// Mutation returns the EMPLOYERUSERINFOMutation object of the builder.
func (ec *EMPLOYERUSERINFOCreate) Mutation() *EMPLOYERUSERINFOMutation {
	return ec.mutation
}

// Save creates the EMPLOYER_USER_INFO in the database.
func (ec *EMPLOYERUSERINFOCreate) Save(ctx context.Context) (*EMPLOYER_USER_INFO, error) {
	var (
		err  error
		node *EMPLOYER_USER_INFO
	)
	if len(ec.hooks) == 0 {
		if err = ec.check(); err != nil {
			return nil, err
		}
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EMPLOYERUSERINFOMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ec.check(); err != nil {
				return nil, err
			}
			ec.mutation = mutation
			if node, err = ec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			if ec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ec.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ec.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*EMPLOYER_USER_INFO)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EMPLOYERUSERINFOMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EMPLOYERUSERINFOCreate) SaveX(ctx context.Context) *EMPLOYER_USER_INFO {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EMPLOYERUSERINFOCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EMPLOYERUSERINFOCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EMPLOYERUSERINFOCreate) check() error {
	return nil
}

func (ec *EMPLOYERUSERINFOCreate) sqlSave(ctx context.Context) (*EMPLOYER_USER_INFO, error) {
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ec *EMPLOYERUSERINFOCreate) createSpec() (*EMPLOYER_USER_INFO, *sqlgraph.CreateSpec) {
	var (
		_node = &EMPLOYER_USER_INFO{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: employer_user_info.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employer_user_info.FieldID,
			},
		}
	)
	return _node, _spec
}

// EMPLOYERUSERINFOCreateBulk is the builder for creating many EMPLOYER_USER_INFO entities in bulk.
type EMPLOYERUSERINFOCreateBulk struct {
	config
	builders []*EMPLOYERUSERINFOCreate
}

// Save creates the EMPLOYER_USER_INFO entities in the database.
func (ecb *EMPLOYERUSERINFOCreateBulk) Save(ctx context.Context) ([]*EMPLOYER_USER_INFO, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*EMPLOYER_USER_INFO, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EMPLOYERUSERINFOMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EMPLOYERUSERINFOCreateBulk) SaveX(ctx context.Context) []*EMPLOYER_USER_INFO {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EMPLOYERUSERINFOCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EMPLOYERUSERINFOCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
