// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"griffin-dao/ent/payment_history"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// PAYMENT_HISTORY is the model entity for the PAYMENT_HISTORY schema.
type PAYMENT_HISTORY struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PAYMENT_HISTORY) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case payment_history.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PAYMENT_HISTORY", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PAYMENT_HISTORY fields.
func (ph *PAYMENT_HISTORY) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case payment_history.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ph.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this PAYMENT_HISTORY.
// Note that you need to call PAYMENT_HISTORY.Unwrap() before calling this method if this PAYMENT_HISTORY
// was returned from a transaction, and the transaction was committed or rolled back.
func (ph *PAYMENT_HISTORY) Update() *PAYMENTHISTORYUpdateOne {
	return (&PAYMENT_HISTORYClient{config: ph.config}).UpdateOne(ph)
}

// Unwrap unwraps the PAYMENT_HISTORY entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ph *PAYMENT_HISTORY) Unwrap() *PAYMENT_HISTORY {
	_tx, ok := ph.config.driver.(*txDriver)
	if !ok {
		panic("ent: PAYMENT_HISTORY is not a transactional entity")
	}
	ph.config.driver = _tx.drv
	return ph
}

// String implements the fmt.Stringer.
func (ph *PAYMENT_HISTORY) String() string {
	var builder strings.Builder
	builder.WriteString("PAYMENT_HISTORY(")
	builder.WriteString(fmt.Sprintf("id=%v", ph.ID))
	builder.WriteByte(')')
	return builder.String()
}

// PAYMENT_HISTORYs is a parsable slice of PAYMENT_HISTORY.
type PAYMENT_HISTORYs []*PAYMENT_HISTORY

func (ph PAYMENT_HISTORYs) config(cfg config) {
	for _i := range ph {
		ph[_i].config = cfg
	}
}
