// Code generated by ent, DO NOT EDIT.

package employ_type

const (
	// Label holds the string label denoting the employ_type type in the database.
	Label = "employ_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the employ_type in the database.
	Table = "employ_typ_es"
)

// Columns holds all SQL columns for employ_type fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
