// Code generated by ent, DO NOT EDIT.

package employer_user_info

const (
	// Label holds the string label denoting the employer_user_info type in the database.
	Label = "employer_user_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the employer_user_info in the database.
	Table = "employer_user_inf_os"
)

// Columns holds all SQL columns for employer_user_info fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
