// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CRYPTO_CURRENCY is the predicate function for crypto_currency builders.
type CRYPTO_CURRENCY func(*sql.Selector)

// CRYPTO_PRC_SOURCE is the predicate function for crypto_prc_source builders.
type CRYPTO_PRC_SOURCE func(*sql.Selector)

// EMPLOYEE is the predicate function for employee builders.
type EMPLOYEE func(*sql.Selector)

// EMPLOYER_USER_INFO is the predicate function for employer_user_info builders.
type EMPLOYER_USER_INFO func(*sql.Selector)

// EMPLOY_TYPE is the predicate function for employ_type builders.
type EMPLOY_TYPE func(*sql.Selector)

// PAYMENT_HISTORY is the predicate function for payment_history builders.
type PAYMENT_HISTORY func(*sql.Selector)
